### ISSUE TITLE
インストールできません。

### ISSUE THREAD

**Issue by mg400max** [MicrosoftDocs/azure-docs-powershell.ja-JP#5]
警告: URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' から '' へダウンロードできません。
警告: 利用可能なプロバイダーの一覧をダウンロードできません。インターネット接続を確認してください。

と出てページの通りにしてもインストールができません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 03079670-9757-b2e0-2d1c-f672d08305cc
* Version Independent ID: bd4fb194-d6af-e442-5ced-793e09c3fa83
* Content: [PowerShellGet を使用して Azure PowerShell をインストールする](https://docs.microsoft.com/ja-jp/powershell/azure/install-az-ps?view=azps-4.2.0)
* Content Source: [docs-conceptual/azps-4.2.0/install-az-ps.md](https://github.com/MicrosoftDocs/azure-docs-powershell.ja-jp/blob/live/docs-conceptual/azps-4.2.0/install-az-ps.md)
* GitHub Login: @mikefrobbins
* Microsoft Alias: **mirobb**

**Comment by srvbpigh** [comment]
Hello, @mg400max
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@mg400max  様、

ご投稿いただき、ありがとうございます。このフィードバックは製品に関連しているようです。ドキュメント ページの下部にある [製品フィードバックを送る] ボタンを使用して、提案を記録してください。

ドキュメントに関連したフィードバックがある場合は、このチャネルを通して記録してください。

記事への投稿に感謝しております。

Microsoft DOCS International Team
